import JSZip from 'jszip'

import { generateSedmlData } from './export/sedml'
import { buildManifestXml } from './export/omex'
import { buildSimulationJson } from './export/simulation'

import { useOmexStore } from '../stores/omexStore.js'

// Helper: Converts a Blob to a pure Base64 string (strips the "data:..." prefix)
const blobToBase64 = (blob) => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onloadend = () => {
      // reader.result is like "data:application/zip;base64,UEsDB..."
      // We only want the part after the comma
      const splitResult = reader.result.split(',')
      const base64data = reader.result.split(',')[1]
      resolve(base64data)
    }
    reader.onerror = reject
    reader.readAsDataURL(blob)
  })
}

export const base64ToBlob = async (base64data, mimeType = 'application/zip') => {
  const dataUrl = `data:${mimeType};base64,${base64data}`
  const res = await fetch(dataUrl)
  return await res.blob()
}

async function gzipBlob(blob) {
  const stream = blob.stream().pipeThrough(new CompressionStream('gzip'))
  return await new Response(stream).blob()
}

async function gunzipBlob(blob) {
  const stream = blob.stream().pipeThrough(new DecompressionStream('gzip'))
  return await new Response(stream).blob()
}

export const utf8ToGzippedBase64 = async (text) => {
  const blob = new Blob([text], { type: 'text/plain' })
  const gzipped = await gzipBlob(blob)
  return await blobToBase64(gzipped)
}

export const base64ToUtf8 = async (base64data) => {
  const compressedBlob = await base64ToBlob(base64data, 'application/gzip')
  const blob = await gunzipBlob(compressedBlob)
  return await blob.text()
}

export async function createCellMLDataFragment(cellmlBlob, fileName) {
  const internalName = fileName ? (fileName.endsWith('.cellml') ? fileName : `${fileName}.cellml`) : 'model.cellml'

  const zip = new JSZip()
  zip.file(internalName, cellmlBlob)

  const zipBlob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 },
  })

  return createDataFragment(zipBlob, 'application/x.vnd.zip-cellml+zip')
}

/**
 * Assembles a minimal COMBINE/OMEX archive — a ZIP containing a manifest,
 * the flattened CellML model, and a SED-ML simulation description — suitable
 * for opening directly in Web OpenCOR.
 *
 * This is intentionally minimal for now: the SED-ML content generated by
 * generateSedmlData() is still a static placeholder rather than being
 * derived from the workspace's actual plot / simulation-settings /
 * parameter-scan configuration (see sedmlExport.js). `simData` is threaded
 * through regardless so that wiring is already in place once
 * generateSedmlData is fleshed out — right now it's simply ignored.
 *
 * @param {object} cellmlData - The flattened CellML model data.
 * @param {object} flowSnapshot - The current workspace flow snapshot (nodes/edges).
 * @param {object} [simData] - Simulation/plot/parameter-scan config for the SED-ML doc. Currently unused by generateSedmlData.
 * @param {object} [addInfo] - Additional information not carried by the other parameters.
 * @returns {Promise<Blob>} The .omex archive as a zip Blob.
 */
export async function generateOmexArchive(cellmlData, flowSnapshot, simData = {}, addInfo = {}) {
  const omexStore = useOmexStore()

  const cellmlFileName = addInfo.cellmlFileName
  const sedmlText = generateSedmlData(simData.simulationSettings, cellmlFileName)
  const simulationJson = buildSimulationJson(simData.plotConfig, simData.parameterScanConfig, addInfo.extractedData)

  const reservedLocations = new Set(['manifest.xml', 'document.sedml', cellmlFileName, 'flow-snapshot.json', 'changes.json'])

  const manifestEntries = [
    { location: 'document.sedml', format: 'http://identifiers.org/combine.specifications/sed-ml', master: true },
    { location: cellmlFileName, format: 'http://identifiers.org/combine.specifications/cellml' },
    { location: 'flow-snapshot.json', format: 'application/x.vnd.phlynx-flow+json' },
    { location: 'changes.json', format: 'application/x.vnd.phlynx-changes+json' },
  ]
  if (simulationJson !== null) {
    manifestEntries.push({ location: 'simulation.json', format: 'http://purl.org/NET/mediatypes/application/json' })
  }

  omexStore.preservedExtras.forEach((extra) => {
    if (!reservedLocations.has(extra.location)) {
      manifestEntries.push({ location: extra.location, format: extra.format })
    }
  })

  const manifestXml = buildManifestXml(manifestEntries)

  const zip = new JSZip()
  zip.file('manifest.xml', manifestXml)
  zip.file(cellmlFileName, cellmlData.blob)
  zip.file('document.sedml', sedmlText)
  zip.file('flow-snapshot.json', flowSnapshot)
  zip.file('changes.json', JSON.stringify({ id: 'phlynx-changes', version: '1.0.0', modified: addInfo.modified }))

  if (simulationJson !== null) {
    zip.file('simulation.json', simulationJson)
  }

  for (const extra of omexStore.preservedExtras) {
    if (!reservedLocations.has(extra.location)) {
      zip.file(extra.location, extra.payload)
    }
  }

  return zip.generateAsync({ type: 'blob' })
}

export async function createOmexDataFragment(omexBlob) {
  return createDataFragment(omexBlob, 'application/zip')
}

export async function createDataFragment(zipBlob, mimeType) {
  const base64String = await blobToBase64(zipBlob)

  return `data:${mimeType};base64,${base64String}`
}
