name: Create Staging PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          path: source
          fetch-depth: 0 # Fetching all history to find tags.

      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          path: production
          ref: production

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Enable corepack
        run: corepack enable yarn

      - name: Enable yarn cache
        uses: actions/setup-node@v7
        with:
          cache: 'yarn'
          cache-dependency-path: 'source/yarn.lock'

      - name: Install Dependencies
        run: |
          cd source

          yarn

      - name: Generate Changelog
        id: gen_changelog
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd source

          LAST_TAG=$(git describe --tags --abbrev=0 origin/main 2>/dev/null || echo "")
          COUNT=`git rev-list --count $(git describe --tags --match "v*" --abbrev=0)..HEAD`

          yarn gen-changelog -q > changelogs/latest.md

          # Check if latest.md is empty or only whitespace.
          if grep -q '[^[:space:]]' "changelogs/latest.md"; then
            echo "Generated changelogs/latest.md has content."
          else
            # If the file exists, delete it (using -f to avoid errors if it's already gone)
            if [ -f "changelogs/latest.md" ]; then
              echo "File was empty or only whitespace. Deleting."
              rm "changelogs/latest.md"
            else
              echo "File changelogs/latest.md does not exist, doing nothing."
            fi
          fi

          yarn update:docs:changelog

          echo "last_tag=$LAST_TAG" >> $GITHUB_OUTPUT
          echo "commit_count=$COUNT" >> $GITHUB_OUTPUT

      - name: Update Production Branch
        run: |
          rsync -a --delete --exclude='.git' source/ production/

      - name: Commit Changes
        id: commit_changes
        run: |
          cd production

          # Configure git identity
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Commit changes.
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "ci: stage PR."
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and Push Staging Branch
        if: steps.commit_changes.outputs.changes == 'true'
        id: create_branch
        run: |
          cd production

          SHORT_SHA=$(git rev-parse --short HEAD)
          BRANCH_NAME="staging-${SHORT_SHA}"

          # Create branch.
          git checkout -b "$BRANCH_NAME"

          # Push branch
          git push origin "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.commit_changes.outputs.changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.PAT_CREATE_PR }}
        run: |
          cd production

          COMMIT_COUNT=${{ steps.gen_changelog.outputs.commit_count }}
          BRANCH_NAME=${{ steps.create_branch.outputs.branch_name }}
          LAST_TAG=${{ steps.gen_changelog.outputs.last_tag }}
          TITLE="Staging for release: $LAST_TAG"

          if [ "$COMMIT_COUNT" -gt 0 ]; then
            # Read the file content into a variable for the PR body
            if [ -f "changelogs/latest.md" ]; then
              BODY_CONTENT=$(cat changelogs/latest.md)
            else
              BODY_CONTENT="No changelog available."
            fi
            TITLE+=" + Post Release Changes"
          else
            BODY_CONTENT="Release $LAST_TAG of PhLynx."
          fi

          gh pr create \
            --base production \
            --head "$BRANCH_NAME" \
            --title "$TITLE" \
            --body "$BODY_CONTENT" \
            --draft=false
